---
title: "О пространстве имен исключений"
sidebar_label: "исключения"
id: "исключения"
description: "Вызывайте предупреждения/ошибки с помощью пространства имен `исключения`."
---

Пространство имен `исключения` может использоваться для вызова предупреждений и ошибок в пользовательском пространстве dbt.

## raise_compiler_error

Метод `exceptions.raise_compiler_error` вызовет ошибку компилятора с предоставленным сообщением. Это обычно полезно только в макросах или <Term id="materialization">материализациях</Term>, когда вызывающая модель передает недопустимые аргументы. Обратите внимание, что выбрасывание исключения приведет к сбою модели, поэтому используйте эту переменную с осторожностью!

__Пример использования__:

<File name='exceptions.sql'>

```sql
{% if number < 0 or number > 100 %}
  {{ exceptions.raise_compiler_error("Недопустимое `number`. Получено: " ~ number) }}
{% endif %}
```

</File>

## warn

Метод `exceptions.warn` вызовет предупреждение компилятора с предоставленным сообщением, но любая модель все равно будет успешной и будет считаться УСПЕШНОЙ. Если флаг `--warn-error` передан dbt, то это предупреждение будет повышено до исключения, которое будет вызвано.

__Пример использования__:

<File name='warn.sql'>

```sql
{% if number < 0 or number > 100 %}
  {% do exceptions.warn("Недопустимое `number`. Получено: " ~ number) %}
{% endif %}
```

</File>